package com.mediassist;

import com.mediassist.service.MeddiesPdfGeneratorService;
import com.mediassist.service.PdfExtractionService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class MeddiesPdfGeneratorServiceTest {

    private MeddiesPdfGeneratorService generatorService;
    private PdfExtractionService pdfExtractionService;

    @BeforeEach
    void setUp() {
        generatorService = new MeddiesPdfGeneratorService();
        pdfExtractionService = new PdfExtractionService();
    }

    @Test
    @DisplayName("Should generate valid hospital lab report PDF with patient demographics and indicators")
    void testGenerateRandomMeddiesPdf() {
        MeddiesPdfGeneratorService.GeneratedPdfResult result = generatorService.generateRandomMeddiesPdf();

        assertNotNull(result);
        assertNotNull(result.getFileName());
        assertTrue(result.getFileName().endsWith(".pdf"), "File name must end with .pdf");
        assertNotNull(result.getPatientName());
        assertFalse(result.getPatientName().isBlank());

        byte[] pdfBytes = result.getPdfBytes();
        assertNotNull(pdfBytes);
        assertTrue(pdfBytes.length > 500, "PDF bytes should be at least 500 bytes");

        // Verify valid PDF magic bytes (%PDF-)
        String header = new String(pdfBytes, 0, Math.min(pdfBytes.length, 10), java.nio.charset.StandardCharsets.ISO_8859_1);
        assertTrue(header.startsWith("%PDF-"), "Generated byte array must start with %PDF- header");

        // Verify PDF extraction can extract text from the generated PDF
        String extractedText = pdfExtractionService.extractTextFromPdf(pdfBytes);
        assertNotNull(extractedText);
        assertFalse(extractedText.isBlank());
        assertTrue(extractedText.contains("KET QUA XET NGHIEM"), "Extracted text should contain document title");
        assertTrue(extractedText.contains("THONG TIN BENH NHAN"), "Extracted text should contain patient section");
        assertTrue(extractedText.contains("BANG CHI SO CAN LAM SANG"), "Extracted text should contain lab indicators table");
    }

    @Test
    @DisplayName("Should generate valid PDF resiliently across multiple invocations")
    void testMultipleRandomInvocations_AllProduceValidPdf() {
        for (int i = 0; i < 3; i++) {
            MeddiesPdfGeneratorService.GeneratedPdfResult result = generatorService.generateRandomMeddiesPdf();
            assertNotNull(result);
            assertNotNull(result.getPdfBytes());
            assertTrue(result.getPdfBytes().length > 1000, "PDF size must be > 1KB");
            String header = new String(result.getPdfBytes(), 0, 5, java.nio.charset.StandardCharsets.ISO_8859_1);
            assertEquals("%PDF-", header);
        }
    }
}
