/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b0c9e8",
        "secondary-fixed": "#89f5e7",
        "primary-container": "#0f2942",
        "surface-variant": "#d3e4fe",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#001d31",
        "on-surface": "#0b1c30",
        "on-tertiary-fixed-variant": "#004b73",
        "tertiary-fixed": "#cce5ff",
        "on-secondary-fixed-variant": "#005049",
        "on-primary-container": "#7991af",
        "tertiary-fixed-dim": "#93ccff",
        "on-secondary-container": "#006f66",
        "on-primary-fixed": "#011d35",
        "surface-bright": "#f8f9ff",
        "surface": "#f8f9ff",
        "secondary-fixed-dim": "#6bd8cb",
        "surface-container-low": "#eff4ff",
        "on-surface-variant": "#43474d",
        "inverse-surface": "#213145",
        "tertiary-container": "#002a44",
        "background": "#f8f9ff",
        "secondary-container": "#86f2e4",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container": "#e5eeff",
        "surface-dim": "#cbdbf5",
        "tertiary": "#001524",
        "error-container": "#ffdad6",
        "primary": "#001428",
        "secondary": "#006a61",
        "on-error": "#ffffff",
        "on-background": "#0b1c30",
        "on-tertiary-container": "#2e95da",
        "primary-fixed": "#d1e4ff",
        "on-primary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-primary-fixed-variant": "#314863",
        "inverse-on-surface": "#eaf1ff",
        "outline-variant": "#c3c6ce",
        "outline": "#74777e",
        "inverse-primary": "#b0c9e8",
        "surface-tint": "#49607c",
        "error": "#ba1a1a",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed": "#00201d",
        medical: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          500: '#14b8a6',
          600: '#0d9488',
          700: '#0f766e',
        }
      },
      spacing: {
        "space-xs": "0.5rem",
        "gutter-sm": "1rem",
        "gutter": "1.5rem",
        "margin": "2rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem",
        "space-2xs": "0.25rem",
        "space-2xl": "3rem",
        "margin-sm": "1rem",
        "space-md": "1rem",
        "space-sm": "0.75rem"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      boxShadow: {
        "xs": "0 1px 2px 0 rgba(15, 41, 66, 0.05)",
      }
    },
  },
  plugins: [],
}
